"""Automatic database backups with verification, retention and health status.

* The dump is Frappe's own (`mariadb-dump --single-transaction`, gzip), so a consistent snapshot is
  taken while the pharmacy keeps selling; live database files are never copied.
* Backups are encrypted when System Settings → Encrypt Backups is on. The passphrase is generated by
  Frappe into the server's site config, never into source code. Keep a copy of it offline: without
  it an encrypted backup cannot be restored.
* Every run is recorded in *PharmacyOS Backup Log* (an audit trail; it cannot be edited from the UI).
* A failure is logged and reported to authorized users; it never raises into the sale being made.
"""

import gzip
import hashlib
import json
import os
import shutil
from datetime import timedelta

import frappe
from frappe import _
from frappe.utils import cint, get_datetime, now_datetime

from pharmacyos_erp.backup.paths import BACKUPS, data_dir, sub_dir

DB_FILE = "database.sql.gz"
FILES_FILE = "files.tar"
PRIVATE_FILES_FILE = "private-files.tar"
METADATA = "metadata.json"
MANAGE_ROLES = ("System Manager", "Pharmacy Owner")
STATUS_ROLES = ("System Manager", "Pharmacy Owner", "Pharmacy Manager")


def _settings():
	return frappe.get_cached_doc("PharmacyOS Settings")


def sha256(path: str) -> str:
	digest = hashlib.sha256()
	with open(path, "rb") as f:
		for chunk in iter(lambda: f.read(1024 * 1024), b""):
			digest.update(chunk)
	return digest.hexdigest()


def is_encrypted(path: str) -> bool:
	with open(path, "rb") as f:
		return f.read(2) != b"\x1f\x8b"  # gpg output is not a gzip stream


def free_disk_mb(path: str) -> int:
	return int(shutil.disk_usage(path).free / (1024 * 1024))


def _new_folder(stamp) -> str:
	day = sub_dir(BACKUPS, stamp.strftime("%Y-%m-%d"))
	folder = os.path.join(day, stamp.strftime("%H-%M"))
	if os.path.exists(folder):  # second backup in the same minute
		folder = os.path.join(day, stamp.strftime("%H-%M-%S"))
	os.makedirs(folder)
	return folder


def _app_versions() -> dict:
	from frappe.utils.change_log import get_versions

	return {app: v.get("version") for app, v in get_versions().items()}


def run_backup(kind: str = "Hourly", with_files: bool = False) -> str | None:
	"""Take, verify and record one backup. Returns the log name; never raises."""
	from frappe.utils.backups import new_backup
	from frappe.utils.synchronization import filelock

	log = frappe.get_doc({"doctype": "PharmacyOS Backup Log", "kind": kind, "status": "Running"})
	log.started_on = now_datetime()
	log.insert(ignore_permissions=True)
	frappe.db.commit()
	try:
		with filelock("pharmacyos_backup", timeout=5):
			root = data_dir()
			minimum = cint(_settings().min_free_disk_mb)
			if minimum and free_disk_mb(root) < minimum:
				frappe.throw(
					_("Not enough free disk space for a backup ({0} MB free).").format(free_disk_mb(root))
				)
			folder = _new_folder(log.started_on)
			# saved before the dump, so a restored or interrupted row can still be reconciled
			log.db_set("backup_path", folder, commit=True)
			new_backup(
				ignore_files=not with_files,
				backup_path_db=os.path.join(folder, DB_FILE),
				backup_path_files=os.path.join(folder, FILES_FILE),
				backup_path_private_files=os.path.join(folder, PRIVATE_FILES_FILE),
				ignore_conf=True,  # site config holds secrets; it is never copied into backups
				compress=True,
				force=True,
			)
			metadata = write_metadata(folder, log, kind)
			result = verify_backup(folder)
			if not result["ok"]:
				frappe.throw(_("Backup verification failed: {0}").format("; ".join(result["errors"])))
			log.update(
				{
					"status": "Success",
					"verified": 1,
					"encrypted": metadata["encrypted"],
					"size_bytes": sum(f["size"] for f in metadata["files"]),
					"checksum": metadata["files"][0]["sha256"],
				}
			)
	except Exception as e:
		frappe.db.rollback()
		log.status = "Failed"
		log.error = str(e)[:1000]
		frappe.log_error(title=_("PharmacyOS backup failed"))
	log.finished_on = now_datetime()
	log.save(ignore_permissions=True)
	frappe.db.commit()
	return log.name


def write_metadata(folder: str, log, kind: str) -> dict:
	files = []
	for name in (DB_FILE, FILES_FILE, PRIVATE_FILES_FILE):
		path = os.path.join(folder, name)
		if os.path.exists(path):
			files.append({"name": name, "size": os.path.getsize(path), "sha256": sha256(path)})
	settings = _settings()
	metadata = {
		"format": "pharmacyos-backup/1",
		"site": frappe.local.site,
		"pharmacy": settings.pharmacy_name,
		"kind": kind,
		"created_at": get_datetime(log.started_on).isoformat(),
		"time_zone": frappe.db.get_single_value("System Settings", "time_zone"),
		"app_versions": _app_versions(),
		"encrypted": bool(files and is_encrypted(os.path.join(folder, DB_FILE))),
		"files": files,
		"log": log.name,
	}
	with open(os.path.join(folder, METADATA), "w") as f:
		json.dump(metadata, f, indent=1)
	return metadata


def verify_backup(folder: str) -> dict:
	"""Check checksums against metadata and that an unencrypted dump decompresses completely."""
	errors = []
	meta_path = os.path.join(folder, METADATA)
	if not os.path.exists(meta_path):
		return {"ok": False, "errors": [_("metadata.json is missing")]}
	with open(meta_path) as f:
		metadata = json.load(f)
	if not any(f["name"] == DB_FILE for f in metadata.get("files", [])):
		errors.append(_("database dump is missing"))
	for entry in metadata.get("files", []):
		path = os.path.join(folder, entry["name"])
		if not os.path.exists(path):
			errors.append(_("{0} is missing").format(entry["name"]))
		elif sha256(path) != entry["sha256"]:
			errors.append(_("{0} is damaged (checksum mismatch)").format(entry["name"]))
	db = os.path.join(folder, DB_FILE)
	if not errors and not metadata.get("encrypted"):
		try:
			with gzip.open(db, "rb") as f:
				tail = b""
				for chunk in iter(lambda: f.read(1024 * 1024), b""):
					tail = (tail + chunk)[-4096:]
			if b"Dump completed" not in tail and b"COMMIT" not in tail.upper():
				errors.append(_("database dump looks incomplete"))
		except (OSError, EOFError) as e:
			errors.append(_("database dump cannot be read: {0}").format(e))
	return {"ok": not errors, "errors": errors, "metadata": metadata}


def list_backups() -> list[dict]:
	"""Backup folders on disk, newest first, with their metadata (None when unreadable)."""
	root = os.path.join(data_dir(), BACKUPS)
	out = []
	if not os.path.isdir(root):
		return out
	for day in sorted(os.listdir(root), reverse=True):
		day_path = os.path.join(root, day)
		if not os.path.isdir(day_path):
			continue
		for slot in sorted(os.listdir(day_path), reverse=True):
			folder = os.path.join(day_path, slot)
			meta = None
			try:
				with open(os.path.join(folder, METADATA)) as f:
					meta = json.load(f)
			except OSError, ValueError:
				pass
			out.append({"folder": folder, "day": day, "slot": slot, "metadata": meta})
	return out


def apply_retention(now=None) -> list[str]:
	"""Delete expired backup folders. Keeps every backup for `keep_hourly_days`, the last backup of
	each day for `keep_daily_days`, and always the newest verified backup. Returns deleted folders."""
	settings = _settings()
	now = get_datetime(now or now_datetime())
	hourly_cutoff = (now - timedelta(days=cint(settings.keep_hourly_days) or 2)).strftime("%Y-%m-%d")
	daily_cutoff = (now - timedelta(days=cint(settings.keep_daily_days) or 30)).strftime("%Y-%m-%d")
	backups = list_backups()
	good = [b for b in backups if b["metadata"] and b["metadata"].get("files")]
	protected = {good[0]["folder"]} if good else set()
	last_of_day = {}
	for b in good:  # newest first, so the first seen per day is that day's last backup
		last_of_day.setdefault(b["day"], b["folder"])
	deleted = []
	for b in backups:
		if b["folder"] in protected or b["day"] >= hourly_cutoff:
			continue
		if b["day"] >= daily_cutoff and last_of_day.get(b["day"]) == b["folder"]:
			continue
		shutil.rmtree(b["folder"], ignore_errors=True)
		deleted.append(b["folder"])
	for day in {b["day"] for b in backups}:  # remove emptied day folders
		day_path = os.path.join(data_dir(), BACKUPS, day)
		if os.path.isdir(day_path) and not os.listdir(day_path):
			os.rmdir(day_path)
	return deleted


# --------------------------------------------------------------------------- scheduler


def reconcile_running(older_than_minutes: int = 120) -> int:
	"""Settle log rows left "Running" by a power cut, a crash or a restore (the restored database holds
	the row as it was mid-backup). The files on disk decide: verified → Success, else Failed."""
	cutoff = now_datetime() - timedelta(minutes=older_than_minutes)
	count = 0
	for log in frappe.get_all(
		"PharmacyOS Backup Log",
		filters={"status": "Running", "started_on": ["<", cutoff]},
		fields=["name", "backup_path"],
	):
		ok = bool(log.backup_path and os.path.isdir(log.backup_path) and verify_backup(log.backup_path)["ok"])
		values = (
			{"status": "Success", "verified": 1}
			if ok
			else {
				"status": "Failed",
				"error": _("Interrupted before completion (server restart, power loss or restore)."),
			}
		)
		frappe.db.set_value("PharmacyOS Backup Log", log.name, values, update_modified=False)
		count += 1
	frappe.db.commit()
	return count


def hourly():
	from pharmacyos_erp.backup.snapshots import prune_snapshots, write_sales_snapshot

	reconcile_running()
	settings = _settings()
	if cint(settings.enable_hourly_backup):
		run_backup("Hourly")
		apply_retention()
	if cint(settings.enable_sales_snapshots):
		try:
			write_sales_snapshot()
			prune_snapshots()
		except Exception:
			frappe.log_error(title=_("PharmacyOS sales snapshot failed"))


def daily():
	from pharmacyos_erp.backup.snapshots import write_daily_snapshot

	if cint(_settings().enable_hourly_backup):
		run_backup("Daily", with_files=True)
	try:
		write_daily_snapshot(frappe.utils.add_days(frappe.utils.nowdate(), -1))
	except Exception:
		frappe.log_error(title=_("PharmacyOS daily snapshot failed"))


# --------------------------------------------------------------------------- status & actions


def _last(status=None, kinds=("Hourly", "Daily", "Manual", "Safety")):
	filters = {"kind": ["in", kinds]}
	if status:
		filters["status"] = status
	rows = frappe.get_all(
		"PharmacyOS Backup Log",
		filters=filters,
		fields=["name", "kind", "status", "started_on", "finished_on", "backup_path", "size_bytes", "error"],
		order_by="started_on desc",
		limit_page_length=1,
	)
	return rows[0] if rows else None


def backup_health() -> dict:
	settings = _settings()
	last_ok = _last("Success")
	last_any = _last()
	now = now_datetime()
	failing = bool(last_any and last_any.status == "Failed")
	stale = not last_ok or (now - get_datetime(last_ok.finished_on or last_ok.started_on)) > timedelta(
		hours=2
	)
	enabled = bool(cint(settings.enable_hourly_backup))
	try:
		folder, free = data_dir(), None
		free = free_disk_mb(folder)
	except Exception:
		folder = None
	state = "protected" if enabled and not failing and not stale else "warning"
	return {
		"state": state,
		"enabled": enabled,
		"last_success": last_ok,
		"last_error": last_any.error if failing else None,
		"next_run": (now.replace(minute=0, second=0, microsecond=0) + timedelta(hours=1))
		if enabled
		else None,
		"folder": folder,
		"free_disk_mb": free,
	}


@frappe.whitelist()
def get_backup_status() -> dict:
	frappe.only_for(STATUS_ROLES)
	return backup_health()


@frappe.whitelist(methods=["POST"])
def backup_now() -> str:
	frappe.only_for(MANAGE_ROLES)
	frappe.enqueue(
		"pharmacyos_erp.backup.service.run_backup",
		queue="long",
		kind="Manual",
		job_id="pharmacyos-backup-now",
		deduplicate=True,
	)
	return "queued"


def health_check() -> dict:
	"""Post-restore / post-update smoke check (run with `bench execute`)."""
	checks = {
		"database": bool(frappe.db.sql("select 1")),
		"items": frappe.db.count("Item"),
		"settings": bool(frappe.db.exists("DocType", "PharmacyOS Settings")),
		"scheduler_enabled": bool(cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))),
	}
	# backups and website sync stop silently without the scheduler
	checks["ok"] = checks["database"] and checks["settings"] and checks["scheduler_enabled"]
	print(json.dumps(checks))
	return checks


def record_restore(folder: str) -> None:
	"""Audit entry written by deploy/restore-backup.sh after a successful restore."""
	log = frappe.get_doc(
		{
			"doctype": "PharmacyOS Backup Log",
			"kind": "Restore",
			"status": "Success",
			"started_on": now_datetime(),
			"finished_on": now_datetime(),
			"backup_path": folder,
			"verified": 1,
		}
	)
	log.insert(ignore_permissions=True)
	frappe.db.commit()
	reconcile_running(older_than_minutes=0)
